# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('article_url', models.URLField(max_length=150)),
                ('video_url', models.URLField(max_length=150)),
                ('image_url', models.URLField(max_length=150)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=20)),
                ('hotness_score', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topic'),
        ),
    ]
