# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:54
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('summary', models.TextField()),
                ('article_url', models.URLField(max_length=150)),
                ('video_url', models.URLField(max_length=150)),
                ('image_url', models.URLField(max_length=150)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
                ('category_name', api.models.CategoryEnum(choices=[(0, 'politics'), (1, 'sports'), (2, 'business'), (3, 'entertainent'), (4, 'technology'), (5, 'health'), (6, 'science'), (7, 'other')])),
            ],
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topic'),
        ),
    ]
